apiVersion: v1
kind: LimitRange
metadata:
  name: mylimitrange
  namespace: mynamespace
spec:
  limits:
  - type: Container
    max: # maximum amount of compute resources allowed for a container in the namespace, if exceeds container will not be created
      cpu: "1"
      memory: 512Mi
    min: # minimum amount of compute resources guaranteed for a container in the namespace, if exceeds container will not be created
      cpu: 200m
      memory: 64Mi
    default: # default limit
      cpu: 500m
      memory: 128Mi
    defaultRequest: # default request
      cpu: 250m
      memory: 64Mi